### ISSUE TITLE
Upgraded okhttp dependency has breaking change.

### ISSUE THREAD

**Issue by fathimaSheikh** [snowplow/snowplow-java-tracker#365]
**Describe the bug**
With 4.10 version of okhttp, there's a breaking change with use of function `RequestBody.create(payload, JSON)`. It's changed to `RequestBody.create(JSON, payload)`

** Expect**
Would be great to have the dependency updated and fix complier issue.

** Version **
Works with version 4.9.3
Compiler errors with version 4.10

<img width="858" alt="Screenshot 2023-10-09 at 5 02 10 PM" src="https://github.com/snowplow/snowplow-java-tracker/assets/93930616/ea27427b-c246-413d-aa41-56776ba06a33">
 complete the following information):**

**Comment by matus-tomlein** [comment]
Hi @fathimaSheikh, thank you for the report!

We will definitely update the okhttp dependency to the latest version (4.12), but I am confused about the problem because according to the okhttp code the correct order of the arguments in `RequestBody.create()` is to put the content first and then the content type, [see here](https://github.com/square/okhttp/blob/parent-4.12.0/okhttp/src/main/kotlin/okhttp3/RequestBody.kt#L172-L180). The other order (content type first) that you suggest is deprecated.
